### ISSUE TITLE
join-path does not work well on Windows OS

### ISSUE THREAD

**Issue by patinside** [oscaro/tools-io#1]
When calling join-path on intellij idea on windows 10 OS, result is: 
`(tio/join-path "gs://mybucket" "bar")
=> "gs://mybucket\\bar"`

**Comment by RolT** [comment]
I think the way to fix this is to make `join-path` a protocol dependent multimethod like list-files.

**Comment by jeremy-lc** [comment]
Same error for me, which is harmful since it causes exceptions since Windows does not support double slash
